#!/bin/bash

PIE=/home/maxim/synrc/pie

erl -pa $PIE/deps/gproc/ebin $PIE/deps/sync/ebin $PIE/deps/lager/ebin \
     $PIE/apps/pie/ebin $PIE/apps/msc/ebin $PIE/deps/eslang/ebin \
     +A 100 -config $PIE/sys.config -s pie start $1 $2 $3

stty sane
